# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using file paths relative to the directory where this config file is located.
data:

  # Input table of unaligned fasta files.
  samples: "data/samples.tsv"

# =================================================================================================
#     Pipeline Settings
# =================================================================================================

settings:

  # If set to True, the files in the above samples table are assumed to already be aligned,
  # and the below list of alignment tools is not used.
  skip_alignment: False

  # Select the tool(s) used for sequence alignment.
  # Valid values: "mafft", "muscle"
  aligner:
    - "mafft"
    - "muscle"

  threads: 4

  outdir: "test"
# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:
  # ----------------------------------------------------------------------
  #     mafft
  # ----------------------------------------------------------------------

  mafft:
    threads: 4
    extra: "--auto"

  # ----------------------------------------------------------------------
  #     muscle
  # ----------------------------------------------------------------------

  muscle:
    extra: ""

  # ----------------------------------------------------------------------
  #     ParGenes
  # ----------------------------------------------------------------------

  pargenes:
    # Set the command to run ParGenes, including the python command to execute.
    command: "python3 ~/ParGenes/pargenes/pargenes.py"
    threads: 4

    # Other options to run ParGenes with.
    extra: "--use-modeltest"
    parsimony_starting_trees: 10
    random_starting_trees: 10
    bs_trees: 100
    datatype: "nt" # 'nt' for DNA, 'aa' for protein

  # ----------------------------------------------------------------------
  #     RAxML-ng
  # ----------------------------------------------------------------------

  raxmlng:
    # Set the command to run RAxML-ng. Can re-use the binary from ParGenes, but does not have to.
    command: "~/ParGenes/raxml-ng/bin/raxml-ng"

  # ----------------------------------------------------------------------
  #     IQTree
  # ----------------------------------------------------------------------

  iqtree:
    extra: ""
