# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using file paths relative to the directory where this config file is located.
data:

  # Input table of unaligned fasta files.
  samples: "data/samples.tsv"

# =================================================================================================
#     Pipeline Settings
# =================================================================================================

settings:

  # Select the tool(s) used for sequence alignment.
  # Valid values: "mafft", "muscle"
  aligner:
    - "mafft"
    - "muscle"

# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     mafft
  # ----------------------------------------------------------------------

  mafft:
    threads: 6
    extra: "--auto"

  # ----------------------------------------------------------------------
  #     muscle
  # ----------------------------------------------------------------------

  muscle:
    extra: ""

  # ----------------------------------------------------------------------
  #     ParGenes
  # ----------------------------------------------------------------------

  pargenes:
    # Set the command to run ParGenes, including the python command to execute.
    command: "python3 /home/lczech/GitHub/ParGenes/pargenes/pargenes.py"
    threads: 6

    # Other options to run ParGenes with.
    extra: "--use-modeltest"
    parsimony_starting_trees: 10
    random_starting_trees: 10
    bs_trees: 100

  # ----------------------------------------------------------------------
  #     RAxML-ng
  # ----------------------------------------------------------------------

  raxmlng:
    # Set the command to run RAxML-ng. Can re-use the binary from ParGenes, but does not have to.
    command: "/home/lczech/GitHub/ParGenes/raxml-ng/bin/raxml-ng"
