# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using file paths relative to the directory where this config file is located.
data:

  # Input table of unaligned fasta files.
  samples: "data/samples.tsv"

# =================================================================================================
#     Pipeline Settings
# =================================================================================================

settings:

  # Select the tool(s) used for sequence alignment.
  # Valid values: "mafft", "muscle"
  aligner:
    - "mafft"

# =================================================================================================
#     Tool Parameters
# =================================================================================================

params:

  # ----------------------------------------------------------------------
  #     mafft
  # ----------------------------------------------------------------------

  mafft:
    threads: 6
    extra: "--auto"

  # ----------------------------------------------------------------------
  #     muscle
  # ----------------------------------------------------------------------

  muscle:
    extra: ""

  # ----------------------------------------------------------------------
  #     ParGenes
  # ----------------------------------------------------------------------

  pargenes:
    command: "python /home/lczech/GitHub/ParGenes/pargenes/pargenes.py"
    threads: 6
    extra: "--use-modeltest"
    parsimony_starting_trees: 10
    random_starting_trees: 10
